/// Auto-generated by dioxus-iconify - DO NOT EDIT
/// Generated: 2026-06-05T07:24:35.982501714+00:00
/// Collection: heroicons
/// This is a partial import from Iconify
/// Browse icons: <https://icon-sets.iconify.design/heroicons/>
///
/// ```yaml
/// name: HeroIcons
/// author:
///   name: Refactoring UI Inc
///   url: https://github.com/tailwindlabs/heroicons
/// license:
///   title: MIT
///   spdx: MIT
///   url: https://github.com/tailwindlabs/heroicons/blob/master/LICENSE
/// total: 1288
/// category: UI Other / Mixed Grid
/// palette: false
/// ```
use super::IconData;

#[allow(non_upper_case_globals)]
pub const ArrowLeft: IconData = IconData {
    name: "heroicons:arrow-left",
    body: r###"<path fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M10.5 19.5L3 12m0 0l7.5-7.5M3 12h18"/>"###,
    view_box: "0 0 24 24",
    width: "24",
    height: "24",
};
